# Generated by Django 3.2.7 on 2021-10-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=13)),
                ('date', models.DateField()),
            ],
        ),
    ]
